version: '3.8'
services:
  rainy:
    image: ghcr.io/alexzedim/rainy:latest
    container_name: rainy
    restart: always
    command: [ 'node', 'dist/apps/rainy/main.js' ]
    environment:
      - NODE_ENV=${NODE_ENV}
      - KEY=${KEY}

  pepa-chat-gpt:
    image: ghcr.io/alexzedim/pepa:latest
    container_name: pepa
    restart: always
    command: [ 'node', 'dist/apps/pepa/main.js' ]
    environment:
      - NODE_ENV=${NODE_ENV}
      - KEY=${KEY}

  fefenya:
    image: ghcr.io/alexzedim/fefenya:latest
    container_name: fefenya
    restart: always
    command: [ 'node', 'dist/apps/fefenya/main.js' ]
    environment:
      - NODE_ENV=${NODE_ENV}
      - KEY=${KEY}

  rodriga:
    image: ghcr.io/alexzedim/rodriga:latest
    container_name: rodriga
    restart: always
    command: [ 'node', 'dist/apps/rodriga/main.js' ]
    environment:
      - NODE_ENV=${NODE_ENV}
      - KEY=${KEY}
