export enum CHAT_KEYS_ENUM {
  MENTIONED = 'IS_MENTIONED',
  THREAD = 'THREAD',
  FULL_TILT_IGNORE = 'FULL_TILT_IGNORE',
  LAST_MESSAGE_AT = 'LAST_MESSAGE_AT',
}

export enum IDENTITY_TAGS_ENUM {
  PROVOKE = 'PROVOKE',
  CHAT = 'CHAT',
  QUESTION = 'QUESTION',
  SUBMISSION = 'SUBMISSION',
}

export enum PEPA_PERSONALITY {
  PROVOKE = 'PROVOKE',
  CHAT = 'CHAT',
  QUESTION = 'QUESTION',
  SUBMISSION = 'SUBMISSION',
}

export enum PEPA_QUESTIONS_TYPE {
  LIGHT = 'LIGHT',
  HEAVY = 'HEAVY',
  CERTAIN = 'CERTAIN',
  UNCERTAIN = 'UNCERTAIN',
}

export enum PEPA_ROLL_CHANCE {
  ATTACHMENT_ONLY_EMOJI = 95,
  TEXT_ONLY_PROVOKE = 5,
  TEXT_ONLY_EMOJI = 98,
  IS_MEDIA = 85,
}

export enum PEPA_STORAGE_KEYS {
  EMOJIS = 'PEPA_EMO',
  STICKERS = 'PEPA_STICKER',
  USER = 'PEPA_USER',
}

export enum PEPA_CHAT_KEYS {
  MENTIONED = 'IS_MENTIONED',
  FULL_TILT_IGNORE = 'FULL_TILT_IGNORE',
  LAST_MESSAGE_AT = 'LAST_MESSAGE_AT',
}

export enum PEPA_TRIGGER_FLAG {
  TEST = 'TEST',
  EMOJI = 'EMOJI',
  MESSAGE_REPLY = 'MESSAGE_REPLY',
  MESSAGE_PROVOKE = 'MESSAGE_PROVOKE',
  NEW_YEAR = 'NEW_YEAR',
  LOOT_CLOWN_CHEST = 'LOOT_CLOWN_CHEST',
  ANY_GOOD_LOOT = 'ANY_GOOD_LOOT',
  TIME_TO_RAID_HONEY = 'YES_HONEY',
  RAID_TRIGGER_HAPPY = 'ARE_YOU_NOT_ENTERTAINED',
  DEPLETE_MYTHIC_KEY = 'DEPLETE_MYTHIC_KEY',
  POST_MEME = 'POST_MEME',
  EMPTY = 'EMPTY',
}
